id: PD44474CC
initial_creation_type: input
source_metadata:
  title: Striking the Vital Point in Three Statements
  language: en
  description: 'A series of texts based on the final testament of Garab Dorje, a key
    Dzogchen instruction known as ''Striking the Vital Point in Three Statements''
    (tshig gsum gnad brdegs):'
  volume:
    b63d258a4929464aab4ffef9f0d50b2b:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    c2816d0a2c6a4f5287703a0c402cd752:
      title: The Three Statements that Strike the Vital Point
      parent: Root Text
    5a43281308204151bab15f8c482242a3:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Summary
    687120c8c58f44c09d00b163efc35f61:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    bf6d17504a494f0393f9669a780c2a7d:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    8ab944a18d34488e8c494d7bec6a6d3c:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    1a80a6148efa41eaa22dc8dbc8f79409:
      title: Annotation Commentary on the Special Teaching of the Wise and Glorious
        King
      parent: Special Teaching of the Wise and Glorious King
created_at: '2022-03-01T05:58:24.342884'
last_modified_at: '2022-03-01T05:58:24.342891'
